### ISSUE TITLE
Why is there two "configuration" mechanism?

### ISSUE THREAD

**Issue by almet** [ndp-beers/editor#1]
And one of them (the one in the tab) doesn't seem to impact the recipe.

**Comment by fredericsureau** [comment]
Actually, the "Configuration" tab is used to set defaults values (values that will be used when you create a new recipe).
I guess it should be more clearly mentioned though.

I assumed that one should be able to change most parameters such as efficiency for each recipe separately and not make them global parameters.
BTW, tools such as BeerSmith lets you pre-define Brewery setups with these parameters and then choose which brewery to use for the recipe. This could be a good solution between global config and per-recipe config.

**Comment by almet** [comment]
Okay, thanks for the heads up.

Adding a text would for sure help.

If we decide to have multiple "breweries", then we could add the quantities in percentages, and not in absolute units (Kg, g). I believe it might actually makes more sense?

**Comment by fredericsureau** [comment]
I'm not sure to agree with the percentages values.
You write a recipe for a specific final volume and the resulting beer might not be the same if you change volume and respect the same percentage (eg. difference between 10L recipe and 1000L recipe).
However to simplify scaling recipes, I think a dedicated option could be added.

For me, the final volume is a recipe parameter.
Parameters such as dead volume, boil rate, etc. could be however stored in a "brewery" config that can be reused to avoid repetition of many parameters and simplify modification of these parameters.

**Comment by fredericsureau** [comment]
When I say dedicated option, I mean something like the "scale" button on malt.io:
http://www.malt.io/users/nmargelz/recipes/english-nut-brown-ale
Or like the scale checkbox in JolieBulle

**Comment by almet** [comment]
> The resulting beer might not be the same if you change volume and respect the same percentage (eg. difference between 10L recipe and 1000L recipe).

I'm not sure it really changes anything in terms of recipe creation: do you have any example in mind where it doesn't work?

**Comment by fredericsureau** [comment]
This is debatable:
http://beersmith.com/blog/2014/06/11/scaling-beer-recipes-for-commercial-use-with-beersmith/
Anyways, I find it more handy to define ingredients in volume/weight
For example, how do you describe the hops amounts in percentage ?

**Comment by fredericsureau** [comment]
Maybe, for malts we could link percentage and weight and make the percentage editable? (when updated, the weight is updated too)
This way, if someone feels more comfortable with editing percentages, he can.
The same should be possible with hops and IBUs.
And for the brewery config, when you change the brewery to use, you could be asked if you want to scale the recipe or not.

**Comment by almet** [comment]
That looks all good to me :-)

For hops, that's right, it's quite complicated to express in percentages (some hops don't have any impact on the IBU, and even when they do, the isomerisation rate varies depending the time you let them in).

**Comment by fredericsureau** [comment]
I've split up all the ideas mentioned here into multiple issues:
- #10 Making fermentables % editable
- #9 Making hops IBU editable
- #8 Change volume when changing equipment
- #7 Allow to scale recipe
- #6 Move recipe settings to reusable equipment profile
